import { useEffect, useState } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import { FileText, Shield, AlertTriangle, Clock, Download } from "lucide-react";
import jsPDF from "jspdf";
import { auth } from "../firebase";

import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

function History() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const user = auth.currentUser;

      if (!user) {
        setLoading(false);
        return;
      }

      const token = await user.getIdToken();

      const response = await axios.get( `${import.meta.env.VITE_API_URL}/api/history`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      setReports(response.data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  //  const downloadReport = (report) => {
  //   const reportContent = `
  // PRIVACYLENS ANALYSIS REPORT

  // Policy Name:
  // ${report.policy_name}

  // Risk Score:
  // ${report.risk_score}/100

  // Risk Level:
  // ${report.risk_level}

  // Dark Patterns:
  // ${
  //   report.dark_patterns?.length
  //     ? report.dark_patterns.join(", ")
  //     : "None"
  // }

  // AI Privacy Report:

  // ${report.privacy_report}

  // Generated by PrivacyLens
  // `;

  //   const blob = new Blob(
  //     [reportContent],
  //     {
  //       type: "text/plain",
  //     }
  //   );

  //   const url =
  //     window.URL.createObjectURL(blob);

  //   const a =
  //     document.createElement("a");

  //   a.href = url;

  //   a.download =
  //     `${report.policy_name}.txt`;

  //   a.click();

  //   window.URL.revokeObjectURL(url);
  // };

  const downloadReport = (report) => {
    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text("PrivacyLens Report", 20, 20);

    doc.setFontSize(12);

    doc.text(`Policy Name: ${report.policy_name}`, 20, 40);

    doc.text(`Risk Score: ${report.risk_score}/100`, 20, 50);

    doc.text(`Risk Level: ${report.risk_level}`, 20, 60);

    doc.text("Dark Patterns:", 20, 80);

    doc.text(
      report.dark_patterns?.length ? report.dark_patterns.join(", ") : "None",
      20,
      90,
    );

    doc.text("AI Privacy Report:", 20, 115);

    const lines = doc.splitTextToSize(report.privacy_report, 170);

    doc.text(lines, 20, 125);

    doc.save(`${report.policy_name}.pdf`);
  };

  const getRiskStyle = (risk) => {
    switch (risk) {
      case "Low":
        return "bg-green-100 text-green-700";

      case "Medium":
        return "bg-yellow-100 text-yellow-700";

      case "High":
        return "bg-red-100 text-red-700";

      default:
        return "bg-slate-100 text-slate-700";
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        Loading History...{" "}
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {" "}
      <Sidebar />
      <div className="ml-0 lg:ml-72">
        <Navbar />

        <main className="pt-28 px-6 md:px-8 pb-8">
          <div className="max-w-7xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-10"
            >
              <h1 className="mt-5 text-5xl font-bold text-slate-900">
                Privacy Analysis History
              </h1>

              <p className="mt-4 text-lg text-slate-600 max-w-3xl">
                View all previously analyzed privacy policies, generated
                reports, and risk assessments.
              </p>
            </motion.div>

            <div className="grid md:grid-cols-4 gap-6 mb-8">
              <StatCard
                icon={<FileText size={22} />}
                title="Total Reports"
                value={reports.length}
              />

              <StatCard
                icon={<Shield size={22} />}
                title="Safe Policies"
                value={reports.filter((r) => r.risk_level === "Low").length}
              />

              <StatCard
                icon={<AlertTriangle size={22} />}
                title="Risk Alerts"
                value={reports.filter((r) => r.risk_level === "High").length}
              />

              <StatCard
                icon={<Clock size={22} />}
                title="Last Scan"
                value={reports.length > 0 ? "Recent" : "-"}
              />
            </div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"
            >
              <div className="p-6 border-b border-slate-100">
                <h2 className="text-xl font-semibold text-slate-900">
                  Recent Reports
                </h2>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="text-left px-6 py-4">Policy</th>

                      <th className="text-left px-6 py-4">Risk</th>

                      <th className="text-left px-6 py-4">Score</th>

                      <th className="text-left px-6 py-4">Date</th>

                      <th className="text-left px-6 py-4">Download</th>
                    </tr>
                  </thead>

                  <tbody>
                    {reports.map((report, index) => (
                      <tr
                        key={report.id}
                        className="
                        border-t
                        border-slate-100
                        hover:bg-slate-50
                        transition
                      "
                      >
                        <td className="px-6 py-4 font-medium text-slate-800">
                          {report.policy_name}
                        </td>

                        <td className="px-6 py-4">
                          <span
                            className={`px-3 py-1 rounded-full text-xs font-medium ${getRiskStyle(
                              report.risk_level,
                            )}`}
                          >
                            {report.risk_level}
                          </span>
                        </td>

                        <td className="px-6 py-4 text-slate-700">
                          {report.risk_score}/100
                        </td>

                        <td className="px-6 py-4 text-slate-500">
                          {new Date(report.created_at).toLocaleDateString()}
                        </td>

                        <td className="px-6 py-4">
                          <button
                            onClick={() => downloadReport(report)}
                            className="
                            text-cyan-600
                            hover:text-cyan-700
                          "
                          >
                            <Download size={18} />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </motion.div>

            {reports.length === 0 && (
              <div className="bg-white rounded-3xl border border-slate-200 p-12 text-center mt-8">
                <FileText size={50} className="mx-auto text-slate-300" />

                <h3 className="mt-4 text-xl font-semibold text-slate-900">
                  No Reports Yet
                </h3>

                <p className="mt-2 text-slate-500">
                  Start analyzing privacy policies to build your history.
                </p>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}

function StatCard({ icon, title, value }) {
  return (
    <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm">
      {" "}
      <div className="w-12 h-12 rounded-2xl bg-cyan-50 flex items-center justify-center text-cyan-600">
        {icon}{" "}
      </div>
      <p className="mt-4 text-sm text-slate-500">{title}</p>
      <h3 className="mt-1 text-3xl font-bold text-slate-900">{value}</h3>
    </div>
  );
}

export default History;
